apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmmq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ibmmq
  template:
    metadata:
      labels:
        app: ibmmq
    spec:
      containers:
      - name: ibmmq
        image: pbmqcontainers.azurecr.io/custommq
        ports:
        - containerPort: 1414
          name: listener
        - containerPort: 9158
          name: monitoring
        env:
        - name: LICENSE
          value: "accept"
        - name: MQ_QMGR_NAME
          value: "ORANGE"          
        livenessProbe:
          tcpSocket:
            port: 1414
