global:
  useObjectStatus: true
  useResetQStats: false
  logLevel: INFO 
  pollInterval: 30s
  rediscoverInterval: 1h
prometheus:
  port: 9158
  metricsPath: "/metrics"
  namespace: ibmmq
connection:
    queueManager: ORANGE
    replyQueue: SYSTEM.DEFAULT.MODEL.QUEUE
objects:
    queues:
    - "*"
    channels:
    - "*"
    topics:
    subscriptions:
    showInactiveChannels: false
